[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "django-rest-bible"
version = "0.0.2"
dependencies = [
    "django>=5.0",
    "django-filter>=25.0",
    "djangorestframework>=3.15.0",
    "drf-spectacular>=0.29.0"
]
description = "A Django app for interfacing with the Holy Bible."
readme = "README.md"
license = "BSD-3-Clause"
requires-python = ">= 3.10"
authors = [
    {name = "Uchenna Adubasim", email = "uchadubs@gmail.com"},
]
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 5.0", 
    "Framework :: Django :: 5.1",
    "Framework :: Django :: 5.2",
    "Framework :: Django :: 6.0",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]

[project.urls]
Homepage = "https://github.com/uche-wealth/django-rest-bible"
Issues = "https://github.com/uche-wealth/django-rest-bible/issues"

[tool.setuptools]
packages = ["bible", "bible_api"]
