# Generated by Django 5.2 on 2026-04-13 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "number",
                    models.PositiveIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(db_index=True, max_length=64)),
                ("is_new_testament", models.BooleanField()),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(db_index=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="bible.book",
                    ),
                ),
            ],
            options={
                "ordering": ["book", "number"],
                "unique_together": {("book", "number")},
            },
        ),
        migrations.CreateModel(
            name="Verse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(db_index=True)),
                ("text", models.TextField()),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verses",
                        to="bible.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["chapter", "number"],
                "unique_together": {("chapter", "number")},
            },
        ),
    ]
